apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: wordpress
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 17.0.0
    helm:
      valueFiles:
      - $values/prod/apps/wordpress/value-file.yaml
  - repoURL: 'https://github.com/emiresh/argocd-git.git'
    targetRevision: main
    ref: values
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
