apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: wordpress
  source:
    - chart: wordpress
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 17.0.0
      helm:
        parameters:
        - name: wordpressUsername
          value: iresh
        valueFiles:
        - $values/prod/apps/wordpress/values.yaml
    - repoURL: 'https://github.com/emiresh/argocd-git'
      targetRevision: main
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
