apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: wordpress
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 17.0.0
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
  helm:
    parameters:
    - name: wordpressUsername
      value: iresh
    - name: wordpressPassword
      value: iresh@19989