
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: wordpress
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 17.0.0
    helm:
      values: |
        wordpressUsername: iresh
        wordpressPassword: iresh@1998
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
