apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wordpress
  namespace: argocd
spec:
  description: wordpress
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kube-promethus-stack
  namespace: argocd
spec:
  description: kube-prometheus-stack
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
