apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wordpresss
  namespace: argocd
spec:
  description: wordpress
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'

---


