apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-promethus-stack
  namespace: monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: kube-promethus-stack
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 16.0.0
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated: {}
  syncOptions:
    - CreateNamespace=true