apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-promethus-stack
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: kube-promethus-stack
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 50.0.0
    chart: kube-prometheus-stack
    values: |
      grafana:
        enabled: true
      prometheusOperator:
        enabled: false
      kube-state-metrics:
        enabled: false
      # Disable other components as needed
  syncPolicy:
    automated: {}
  syncOptions:
    - CreateNamespace=true
