apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: nginx
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: nginx
    targetRevision: 15.1.1
    helm:
      parameters:
      - name: replicaCount
        value: "2"
      - name: service.type
        value: "ClusterIP"
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
