apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
spec:
  destination:
    namespace: wordpress
    server: https://kubernetes.default.svc
  project: default
  sources:
    - chart: wordpress
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.0.11
      helm:
        valueFiles:
        - $values/wordpress/wordpress.yaml
    # Values from Git
    - repoURL: 'https://github.com/emiresh/argocd-git'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true